# fly.toml app configuration file generated for sagnik-jana on 2024-01-10T12:31:11+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sagnik-jana"
primary_region = "atl"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.2"

[env]
  APP_ENV = "production"
  DB_CONNECTION = "mysql"
  DB_DATABASE = "my_portfolio"
  DB_HOST = "mysql-sagnik-jana.internal"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
